title: Mr. Kaspar dot com
description: Files for my teacher website
theme: just-the-docs

url: https://mr-kaspar.github.io/mrkaspar_com

<!--
aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
-->
